networks:
  broker:
    name: broker
    external: true

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: openwebui
    volumes:
      - ./data:/app/backend/data
      - ./home/ollama:/root/.ollama
    environment:
      OPENROUTER_API_BASE_URL: ${OPENROUTER_API_BASE_URL}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME_SERVICE}-secure.rule=Host(`${NAME_SERVICE}.${HOSTINGDOMAIN}`)"
      - "traefik.http.routers.${NAME_SERVICE}-secure.tls=true"
      - "traefik.http.routers.${NAME_SERVICE}-secure.entrypoints=web-secured"
      - "traefik.http.routers.${NAME_SERVICE}-secure.tls.certresolver=letsencrypt"
      - "traefik.docker.network=broker"
    networks:
      - broker
      - default
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tunnellm:
    image: robinvandernoord/tunnellm:latest
    ports:
      # host:container, one higher than default to prevent conflict; make sure this is blocked by your firewall!
      - "${TUNNELLM_PORT:-11435}:11434"
    networks:
      - default
    restart: unless-stopped
    environment:
      VERBOSITY: ${TUNNELLM_VERBOSITY:-0}
      ENDPOINT: ${TUNNELLM_ENDPOINT:-http://openwebui:8080/api}
      OPENROUTER_API_KEY: ${TUNNELLM_API_KEY}

  forwardllm:
    image: astral/uv:python3.14-alpine
    ports:
      # host:container, two higher than default to prevent conflict; make sure this is blocked by your firewall!
      - "${FORWARDLLM_PORT:-11436}:11434"
    command: 'uv run https://raw.githubusercontent.com/educationwarehouse/forwardllm/refs/heads/main/app.py'
    networks:
      - default
    restart: unless-stopped
    environment:
      OPENROUTER_API_KEY: ${FORWARDLLM_API_KEY}
      OPENROUTER_ENDPOINT: ${FORWARDLLM_ENDPOINT:-http://openwebui:8080/api}

# volumes:
# open-webui: {}


